server:
  port: 8002

spring:
  application:
    name: mylink-admin

# redis配置
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
  #      password: 123456   # redis没设置密码就不用管

# mysql配置
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
# 分表前：
#  datasource:
#    username: root
#    password: Ljf20031227 # 数据库密码
#    url: jdbc:mysql://127.0.0.1:3306/mylink_database?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      connection-test-query: select 1
#      connection-timeout: 20000
#      idle-timeout: 300000
#      maximum-pool-size: 5
#      minimum-idle: 5

short-link:
  group:
    max-num: 20   # 创建分组最大数量

  flow-limit:
    enable: true
    time-window: 1
    max-access-count: 20  # 流量风控最大qps