server:
  port: 8001

spring:

  # redis配置
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
  #      password: 123456   # redis没设置密码就不用管

  # mysql配置
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml