server:
  port: 8001

spring:

  mvc:
    view:
      prefix: /templates/
      suffix: .html

  # redis配置
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
  #      password: 123456   # redis没设置密码就不用管

  # mysql配置
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml

short-link:
  domain:
    default: nurl.ink:8001
  stats:
    locale:
      amap-key: 0c9f48b986f7729f42b0695dd33fac57

  goto-domain:
    # 域名白名单
    white-list:
      enable: true
      names: '知乎,掘金,博客园,CSDN'
      details:
        - zhihu.com
        - juejin.cn
        - cnblogs.com
        - csdn.net